server:
  port: 8081
spring:
  application:
    name: SpringCloudEurekaOneZoneTwo
eureka:
  instance:
    prefer-ip-address: true
    instance_id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    registry-fetch-interval-seconds: 3
    instance-info-replication-interval-seconds: 3
    eureka-service-url-poll-interval-seconds: 3
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: xian
    availability-zones:
      xian: zone-1,zone-2
    service-url:
      zone-1: http://localhost:8080/eureka/
      zone-2: http://localhost:8081/eureka/