server:
  port: 8085
spring:
  application:
    name: SpringCloudEurekaOneZoneOneService
eureka:
  instance:
    instance_id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    metadata-map:
      zone: zone-2
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: xian
    availability-zones:
      xian: zone-2,zone-1
    service-url:
      zone-1: http://localhost:8080/eureka/
      zone-2: http://localhost:8081/eureka/
